# Generated by Django 3.0.5 on 2020-04-25 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='název')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('name', models.CharField(max_length=255, verbose_name='jméno')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Category', verbose_name='kategorie')),
            ],
            options={
                'verbose_name': 'Závodník',
                'verbose_name_plural': 'Závodníci',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='název')),
                ('start', models.DateTimeField(verbose_name='začátek')),
                ('end', models.DateTimeField(verbose_name='konec')),
            ],
            options={
                'verbose_name': 'Závod',
                'verbose_name_plural': 'Závody',
                'ordering': ('-start',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('name', models.CharField(default='', max_length=255, verbose_name='název')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube video')),
                ('registration', models.BooleanField(default=False, verbose_name='registrace')),
                ('finish', models.BooleanField(default=False, verbose_name='cíl')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Race', verbose_name='závod')),
            ],
            options={
                'verbose_name': 'Úkol',
                'verbose_name_plural': 'Úkoly',
                'ordering': ('-registration', '-finish', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='čas')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Player', verbose_name='závodník')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Task', verbose_name='úkol')),
            ],
            options={
                'verbose_name': 'Čas',
                'verbose_name_plural': 'Časy',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Race', verbose_name='závod'),
        ),
        migrations.AddField(
            model_name='category',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Race', verbose_name='závod'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['uuid'], name='competition_uuid_a176d7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['registration'], name='competition_registr_b7ca2e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['finish'], name='competition_finish_2869eb_idx'),
        ),
    ]
