# Generated by Django 3.0.5 on 2020-04-18 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player_uuid', models.UUIDField()),
                ('player_nickname', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('order', models.IntegerField()),
                ('text', models.TextField()),
                ('registration', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player_uuid', models.UUIDField()),
                ('player_nickname', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Task')),
            ],
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['uuid'], name='competition_uuid_a176d7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['order'], name='competition_order_225f07_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['registration'], name='competition_registr_b7ca2e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['finish'], name='competition_finish_2869eb_idx'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Task'),
        ),
    ]
