# Generated by Django 3.0.5 on 2020-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_category_competitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='qr_code_text',
            field=models.TextField(blank=True, null=True, verbose_name='Text ke QR kódu'),
        ),
    ]
