# Generated by Django 3.0.5 on 2020-04-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20200418_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('name',), 'verbose_name': 'Úkol', 'verbose_name_plural': 'Úkoly'},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='competition_order_225f07_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='název'),
        ),
    ]
