# Generated by Django 3.0.5 on 2020-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_race_qr_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish_failed',
            field=models.TextField(blank=True, null=True, verbose_name='neúspěšný cíl'),
        ),
        migrations.AddField(
            model_name='task',
            name='registration_successful',
            field=models.TextField(blank=True, null=True, verbose_name='registrace úspěšná'),
        ),
    ]
