# Generated by Django 3.0.5 on 2020-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20200418_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='player_category',
            field=models.CharField(default='B', max_length=1, verbose_name='kategorie'),
            preserve_default=False,
        ),
    ]
