# Generated by Django 3.0.5 on 2020-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20200426_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='not_registered_text',
            field=models.TextField(blank=True, null=True, verbose_name='Text pro neregistrované'),
        ),
    ]
