# Generated by Django 3.0.5 on 2020-04-26 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_race_not_registered_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid'),
        ),
    ]
