# Generated by Django 3.0.5 on 2020-04-18 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('order',), 'verbose_name': 'Úkol', 'verbose_name_plural': 'Úkoly'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ('created',), 'verbose_name': 'Čas', 'verbose_name_plural': 'Časy'},
        ),
        migrations.AlterField(
            model_name='task',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='cíl'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(verbose_name='pořadí'),
        ),
        migrations.AlterField(
            model_name='task',
            name='registration',
            field=models.BooleanField(default=False, verbose_name='registrace'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='time',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='čas'),
        ),
        migrations.AlterField(
            model_name='time',
            name='player_nickname',
            field=models.CharField(max_length=255, verbose_name='přezdívka hráče'),
        ),
        migrations.AlterField(
            model_name='time',
            name='player_uuid',
            field=models.UUIDField(verbose_name='UUID hráče'),
        ),
        migrations.AlterField(
            model_name='time',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.Task', verbose_name='úkol'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
