# Generated by Django 3.0.5 on 2020-04-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_time_player_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='youtube_link',
            field=models.CharField(max_length=255, null=True, verbose_name='YouTube video'),
        ),
        migrations.AlterField(
            model_name='time',
            name='player_nickname',
            field=models.CharField(max_length=255, verbose_name='přezdívka'),
        ),
    ]
