# Generated by Django 3.0.5 on 2020-04-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_auto_20200419_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
